### ISSUE TITLE
Aide utilisation

### ISSUE THREAD

**Issue by wilfi00** [ParriauxMaxime/skyquest#1]
Bonjour,

Je souhaiterais utiliser cet outil mais j'ai dû mal à voir comment il fonctionne... 
Serait-il possible d'avoir des exemples ?

Il faut forcément commencer par un pseudo de quelqu'un de proche ? (lieu par exemple ou même lycée par exemple ?)

Merci par avance pour la réponse :)

Johan

**Comment by ParriauxMaxime** [comment]
Hello Joan,

Disclaimer, [Skyblog est officiellement fermé depuis hier](https://lemonde.fr/pixels/visuel/2023/08/21/fin-de-skyblog-l-ado-des-reseaux_6186033_4408996.html), j'imagine que j'arrive trop tard et que cette réponse arrivera après la bataille.

Pour le fonctionnement, oui il faut partir d'un pseudo connu, de préférence quelqu'un de proche. Mais pas nécessairement! 
Beaucoup d'utilisateurs de Skyblog se sont "autodoxxé", précisant généralement leurs années de naissance, leur département, voir leur ville/village. 

Depuis le src/main.ts, tu peux changer le niveau de recursivité pour fetcher et iterer sur les fans de ta cible initial (⚠️au dessus de 3 niveau de profondeur, ça devient très long). 
La data se retrouve dans un [container](https://github.com/ParriauxMaxime/skyquest/blob/main/docker-compose.yml) 
Postgres que tu peux facilement connecter avec le container metabase pour affiner ta recherche (age, code postal). 

Dans mon cas, je suis parti de la soeur d'un ami d'enfance qui a le même âge que ma cible. (Pas le meme college/lycée, environ 100km d'écart).
J'ai du customisé un peu le code pour focus sur la france (l'algérie possède beaucoup de skyblog).
Toujours dans mon cas, j'avais déjà retrouvé le skyblog de ma cible très tôt dans le process (first 10 000 skyblog scrapped), mais après avoir réalisé qu'il n'y avait pas de rate limit sur la plateforme, je me suis laissé ~~un peu~~ emporter.

Dernier tip si tu pensais adapter ce script sur des version "cache" de Skyblog, il faut savoir que Google (et autres SE) n'ont jamais pris la peine d'indexer toute la jungle Skyblog à son époque, c'est donc sans doute voué à l'échec.

Best of luck ! 🙌 

P.S : si un (ex-)ingé Skyrock passe par ici et lis ceci, je suis désolé pour le DDOS. Je ne regrette cependant rien 🥷
